from api.models.database.connector import Connect


def create_incident(**incident):
    """
    Insert a new user into the users table.
    Return the user's autogenerated ID.
    """
    sql = """
        INSERT INTO incidents (
            createdby,
            type,
            location,
            status,
            comment,
            images,
            videos,
            title )
        VALUES (
            %s,%s,%s,%s,%s,%s,%s, %s) RETURNING incident_id;
        """
    try:
        conn = Connect()
        cur = conn.up()
        cur.execute(sql, (
            incident['createdBy'],
            incident['type'],
            incident['location'],
            incident['status'],
            incident['comment'],
            incident['images'],
            incident['videos'],
            incident['title']
        ))
        incident_id = cur.fetchone()
        conn.commit()
        cur.close()
        return incident_id
    except Exception as error:
        return error
    finally:
        conn.down()

def get_all_redflag_incidents():
    """
    Retrieve all redflags with most 
    recent records first.
    """
    sql = """
        SELECT (
            incident_id,
            createdOn,
            createdBy,
            type,
            location,
            status,
            comment,
            images,
            videos,
            title )
        FROM incidents
        WHERE type = 'red-flag'
        ORDER BY createdOn DESC
    """
    try:
        conn = Connect()
        cur = conn.up()
        cur.execute(sql)
        rows = cur.fetchall()
        cur.close()
        return rows
    except Exception as error:
        return error
    finally:
        conn.down()

def get_all_intervention_incidents():
    """
    Retrieve all interventions with most 
    recent records first.
    """
    sql = """
        SELECT (
            incident_id,
            createdOn,
            createdBy,
            type,
            location,
            status,
            comment,
            images,
            videos,
            title )
        FROM incidents
        WHERE type = 'intervention'
        ORDER BY createdOn DESC
    """
    try:
        conn = Connect()
        cur = conn.up()
        cur.execute(sql)
        rows = cur.fetchall()
        cur.close()
        return rows
    except Exception as error:
        return error
    finally:
        conn.down()

def delete_user_by_type_and_user_id(type, user_id):
    """
    Delete all users.
    """
    sql_delete = f"""
        DELETE FROM users
        WHERE type = '{type}'
        AND user_id = {user_id}; 
    """
    try:
        conn = Connect()
        cur = conn.up()
        cur.execute(sql_delete)
        conn.commit()
    except Exception as error:
        return error
    finally:
        conn.down()