from api.models.database.connector import Connect


def create_inicident(**incident):
    """
    Insert a new user into the users table.
    Return the user's autogenerated ID.
    """
    sql = """
        INSERT INTO incidents (
            createdBy,
            type,
            location,
            status,
            comment,
            images,
            videos,
            title )
        VALUES (
            %s,%s,%s,%s,%s,%s, %s ) RETURNING incident_id;
        """
    try:
        conn = Connect()
        cur = conn.up()
        cur.execute(sql, (
            incident['createdBy'],
            incident['type'],
            incident['location'],
            incident['status'],
            incident['comment'],
            incident['images'],
            incident['videos'],
            incident['title']
        ))
        incident_id = cur.fetchone()[0]
        conn.commit()
        cur.close()
        return incident_id
    except Exception as error:
        return error
    finally:
        conn.down()

def get_all_redflag_incidents():
    """
    Retrieve all redflags with most 
    recent records first.
    """
    sql = """
        SELECT (
            incident_id,
            createdOn,
            createdBy,
            type,
            location,
            status,
            comment,
            images,
            videos,
            title )
        FROM incidents
        WHERE type = 'red-flag'
        ORDER BY createdOn DESC
    """
    try:
        conn = Connect()
        cur = conn.up()
        cur.execute(sql)
        rows = cur.fetchall()
        cur.close()
        return rows
    except Exception as error:
        return error
    finally:
        conn.down()

def get_all_intervention_incidents():
    """
    Retrieve all interventions with most 
    recent records first.
    """
    sql = """
        SELECT (
            incident_id,
            createdOn,
            createdBy,
            type,
            location,
            status,
            comment,
            images,
            videos,
            title )
        FROM incidents
        WHERE type = 'intervention'
        ORDER BY createdOn DESC
    """
    try:
        conn = Connect()
        cur = conn.up()
        cur.execute(sql)
        rows = cur.fetchall()
        cur.close()
        return rows
    except Exception as error:
        return error
    finally:
        conn.down()