from api.models.database.connector import Connect


def create_user(**user):
    """
    Insert a new user into the users table.
    Return the user's autogenerated ID.
    """
    sql_select = """
        SELECT username, email 
        FROM users 
        WHERE username = '{0}'
        OR email = '{1}'
    """.format(user['username'], user['email'])

    sql_insert = """
        INSERT INTO users (
            firstname,
            lastname,
            othernames,
            email,
            phonenumber,
            username,
            password,
            isAdmin)
        VALUES (%s,%s,%s,%s,%s,%s,%s,%s)
        RETURNING user_id;
    """
    try:
        conn = Connect()
        cur = conn.up()
        cur.execute(sql_select)    
        rows = cur.fetchall()
        if  rows == []:
            cur.execute(sql_insert,(
                user['firstname'],
                user['lastname'],
                user['othernames'],
                user['email'],
                user['phonenumber'],
                user['username'],
                user['password'],
                user['isAdmin']
            ))
            user_id = cur.fetchone()[0]
            conn.commit()
            result = user_id
        else:
            result = False
        return result
    except Exception as error:
        return error
    finally:
        conn.down()

def get_all_users():
    """
    Retrieve all users.
    
    """
    sql = """
       SELECT (
            user_id,
            firstname,
            lastname,
            othernames,
            email,
            phonenumber,
            username,
            registered,
            isAdmin) 
        FROM users
        ORDER BY registered DESC;
    """

    try:
        conn = Connect()
        cur = conn.up()
        cur.execute(sql)
        rows = cur.fetchall()
        return rows
    except Exception as error:
        return error
    finally:
        conn.down()

def delete_user_by_email(email):
    """
    Delete all users.
    """
    sql_delete = f"""
        DELETE FROM users
        WHERE email = '{email}'; 
    """
    try:
        conn = Connect()
        cur = conn.up()
        cur.execute(sql_delete)
        conn.commit()
    except Exception as error:
        return error
    finally:
        conn.down()